### PR TITLE
Having 'our' hangoutsbot instead of xmikos

### PR DESCRIPTION
**Pull request by 00svbeon**

### CODE REVIEW

**Comment by nylonee** [comment]
It would be worth keeping the xmikos hangupsbot version, as that's a very basic one that many others have built on (including wardellchandler/HangoutsBot and hangoutsbot/hangoutsbot).

It would be awesome if hangoutsbot/hangoutsbot could get a mention somewhere in the readme though, it's probably the most feature-filled one out there at the moment.

**Comment by endofline** [comment]
We are maintaining this fork for reference purposes, so that we always have a definitive wokring copy of the latest hangups to test against. It would be best to issue this PR against tdryer's master.

.

**Comment by 00svbeon** [comment]
True, I'll do

**Comment by 00svbeon** [comment]
Made a PR at tdryer directly. Closing this one

**Pull request closed without merging**
